### ISSUE TITLE
Flipper Front and Back Child Components don't re-render because of Flipper is optimised

### ISSUE THREAD

**Issue by oliver-schoenherr** [VisionistInc/react-flipper#13]
The Flipper Components implements the "shouldComponentUpdate" method. But this prevents re-rendring of this child components in case of state changes in the root container.

Example Gist: https://gist.github.com/oliver-schoenherr/507064c8028bc539a19991173f23d393
React Discussion about this Topic: https://github.com/facebook/react/issues/6515

**Comment by enriquecaballero** [comment]
Working on a fix now. I just realized that `shouldComponentUpdate` shouldn't even be there since the Tile component is defined by subclassing `PureComponent`, which already adds a shallow compare.
